tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# Core utilities
brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "httpie"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "ripgrep-all"
brew "superfile"
brew "tmux"
brew "zoxide"

# GUI apps
cask "visual-studio-code"

# fonts
cask "font-hack-nerd-font"
