# Core utilities
brew "bat"
brew "eza"
brew "fd"
brew "fzf"
brew "httpie"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "ripgrep-all"
brew "superfile"
brew "tmux"
brew "zoxide"

# fonts
cask "font-hack-nerd-font"
